/**
 * Returns KaTeX CSS inlined at build time.
 *
 * The CSS string is generated by scripts/generate-katex-data.mjs and
 * compiled into the package, so this function works in all bundle contexts:
 *   - Node.js scripts
 *   - esbuild CJS bundles (VS Code extension)
 *   - Vite / esbuild ESM bundles (website, CLI)
 *
 * The CSS includes @font-face rules with relative font paths —
 * consumers must either:
 *   (a) serve the katex/dist/fonts directory alongside the CSS, or
 *   (b) use the CDN version (https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css)
 *
 * To refresh the inlined CSS (e.g. after a katex version bump), run:
 *   node packages/preview/scripts/generate-katex-data.mjs
 * before building.
 */

import { KATEX_CSS } from './katex-css-data.js';

export function generateKatexCSS(): string {
  return KATEX_CSS;
}
