export { ThemeColor, CHANGE_COLORS, ChangeStyleInfo, getChangeStyle } from './palette.js';
export { PreviewAuthorColorMap } from './author-colors.js';
export { escapeHtml, sanitizeContentHtml } from './escape-html.js';
export { buildReplacements, findFenceZones, LineOffsetMap } from './replacements.js';
export type { PreviewOptions, FenceZone } from './replacements.js';
export { containsCriticMarkup, renderFenceWithCriticMarkup, changedownPlugin } from './plugin.js';
export type { PluginConfig } from './plugin.js';
export { AuthorColorMap, buildDecorationPlan } from '@changedown/core/host';
export type { DecorationPlan, OffsetDecoration, AuthorDecorationRole, ViewMode } from '@changedown/core/host';
export { generatePreviewCSS, generateViewModeCSS } from './generate-css.js';
export { generateKatexCSS } from './generate-katex-css.js';
export { createPreviewRenderer } from './preview-renderer.js';
export type { PreviewRenderer, PreviewRendererOptions, RenderResult as PreviewRenderResult } from './preview-renderer.js';
